spring:
  # Jdbc Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  # Jpa/hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Kafka Config
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: notification_id
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.type.mapping: productEvent:com.fawry.kafka.events.ProductEvent, registerEvent:com.fawry.kafka.events.RegisterEvent
# Mail Configuration
server:
  port: 2222
custom:
  mail:
    host: smtp.gmail.com
    port: 587
    username: muhammadhussein2312@gmail.com
    password: zxsm iyuy jtze pnkq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
source:
  sender:
    email: muhammadhussein2312@gmail.com

# Eureka Server Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
